### PR TITLE
Support endpoint v2.0

### PR DESCRIPTION
**Pull request by mcetkovsky**
Improve the library by:
- Adding support for v2.0 of AAD endpoints. The initial value is set via Azure::defaultEndPointVersion.
- Grabing most urls from an official /.well-known/openid-configuration endpoint instead of having them hard coded. 
- Resolved duplication of code in AccessToken::__construct and Azure::validateAccessToken.
- Added a helper method to retrieve Microsoft Graph root url from the /.well-known/openid-configuration endpoint.

Support for end points is not ideal as the underlying library does not provide necessary data when calling getBaseAuthorizationUrl, getBaseAccessTokenUrl etc. as the version should be determined by the token's `ver` value but the value nor the token is provided when calling these methods.

### CODE REVIEW

**Comment by hajekj** [comment]
Also do not forget to add your name to the README if you wish ;)

**Comment by mcetkovsky** [comment]
I would also suggest to introduce well-known trusted domain as [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/Microsoft.Identity.Client/Instance/AadAuthority.cs) and allow to query only them (if a domain not in the list, use a hard-coded default).

**Comment by hajekj** [comment]
Originally, I wanted to replicate the ADAL functionality, but it was rather too complicated to implement. The closest thing to ADAL in PHP I found was https://github.com/jamesmcq/oidc-aad-php-library.

I have released 1.4.2 (https://github.com/TheNetworg/oauth2-azure/releases/tag/v1.4.2). Before I merge this PR, the README has to be updated.

**Comment by mcetkovsky** [comment]
README.md updated. Please double check its correctness. I have changed only the parts I am actively using as I have not studied the other use cases at all.

**Comment by ivan-redooc** [comment]
Any news on this PR?

**Comment by eotin** [comment]
Hey guys. 
You did an awesome work on this. Thanks. 
When do you think you will be able to go ahead with this PR ?

**Comment by hajekj** [comment]
I would love to merge this one, but my primary concern is about the use of `getOpenIdConfiguration`. As far as it seems - with every request, it would make a HTTP request to AAD's metadata which could be potentially dangerous for the service - in case of many requests. I wanted to implement at least some file system level caching into TEMP folder, but haven't got around to it. Other than that, I don't mind merging this PR.

/cc: @eotin, @ivan-redooc, @mcetkovsky

**Comment by mcetkovsky** [comment]
> I wanted to implement at least some file system level caching into TEMP folder, but haven't got around to it. Other than that, I don't mind merging this PR.

I have the caching on my wishlist since the beginning but as the project I use the code on does not generate excessive amount of HTTP request its below a priority threshold. I am afraid I won't get a chance to add the caching any time soon.

**Comment by hajekj** [comment]
Understood, makes sense. Okay, so let's do it this way - I will try to prepare the caching on Friday (8th May) and see if I can get it all merged by the end of next week.

**Comment by hajekj** [comment]
I have merged this PR - but there is still some outstanding work, I will try to get it done today.

Thanks for the contribution @mcetkovsky

**Comment by eotin** [comment]
Hi @hajekj , Thanks for the hard work. 
Keep us posted ! I'm eager to use this new release

**Pull request merged**
